#!/usr/bin/env bash

#ddev-generated

## Description: Interact with the API application surface
## Usage: api <connect|ddev-command> [args...]
## Example: "ddev api connect cobrofacil"
## Example: "ddev api describe"

set -euo pipefail

exec "${DDEV_APPROOT}/.ddev/commands/host/surface" api "$@"
