#!/usr/bin/env bash

#ddev-generated

## Description: Interact with the app application surface
## Usage: app <connect|ddev-command> [args...]
## Example: "ddev app connect cobrofacil"
## Example: "ddev app describe"

set -euo pipefail

exec "${DDEV_APPROOT}/.ddev/commands/host/surface" app "$@"
